name: Deploy to Railway

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: Install Railway CLI
        run: curl -fsSL https://railway.app/install.sh | sh

      - name: Verify Railway CLI Version
        run: railway --version

      - name: Ensure Project Exists
        run: |
          echo "Linking to profound-sparkle"
          railway project profound-sparkle || railway project create --name profound-sparkle

      - name: Deploy Application with Docker Compose
        run: |
          echo "Deploying logistics-app with docker-compose"
          railway run docker-compose up --build -d