name: Deploy to Railway

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: Install Railway CLI
        run: curl -fsSL https://railway.app/install.sh | sh

      - name: Verify Railway CLI Version
        run: railway --version

      - name: Deploy Application
        run: |
          echo "Deploying logistics-app to profound-sparkle"
          railway up